### ISSUE TITLE
Is it possible for us to get a higher resolution oracle map?

### ISSUE THREAD

**Issue by JeremyLinky** [saimwani/multiON#7]
Hi! The oracle map's resolution is a little low and I am wondering that is it possible for us to get a higher resolution oracle map? Besides, for different episodes in the same scene, the agents may have different starting heights, which means that the starting floors of the agents may be different, but the oracle map you provide is the same map for the same scene. Could you tell me the reason for that? 

Thanks for your patience!!

**Comment by saimwani** [comment]
You can create higher resolution maps for any scene. See [this](https://github.com/saimwani/multiON/blob/2ba4d25678dff9a990dc5e98ad81fd8c0a1bf15c/habitat/tasks/nav/nav.py#L976) for reference. The validation and test episodes use only the ground floor of the scenes. Note that not all scenes are nicely divided by floor using a simple plane, which is why the cached occupancy maps can be inadequate in a few cases. You can also create occupancy maps on the go using [this](https://github.com/saimwani/multiON/blob/2ba4d25678dff9a990dc5e98ad81fd8c0a1bf15c/habitat/tasks/nav/nav.py#L976) instead of using cached maps if you want higher resolution or better accuracy.

**Comment by JeremyLinky** [comment]
Thanks for your reply! However, I still find that for  2 episodes with the same scene in the val dataset, their heights are different, like the following 2 episodes, could you explain why?
![image](https://user-images.githubusercontent.com/50053052/114022040-ef7d7580-98a3-11eb-9039-d809a5dab7db.png)
![image](https://user-images.githubusercontent.com/50053052/114022110-00c68200-98a4-11eb-9839-09a48638f09e.png)

**Comment by saimwani** [comment]
Like I mentioned before, not all scenes are nicely divided by floor using a simple plane, which is why the cached occupancy maps can be inadequate in a few cases. Some floors can have elevated portions which are higher than the rest of the floor. The oracle maps are only used for bench-marking the performance and much of their advantage comes from object locations rather than occupancy information; if you'd like to use higher resolution and more accurate maps, consider trying out the ProjNeuralMap agent instead.
